name: Rust

on:
  push:
    branches: [ "Production" ]
  pull_request:
    branches: [ "Production" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: rust-file-compressor/cargo build --verbose
    - name: Run tests
      run: rust-file-compressor/cargo test --verbose
